config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "welcome#index"
  get 'auth/linkedin', as: :sign_in_with_linkedin
  get 'auth/linkedin/callback' => 'callbacks#linkedin'

  resources :posts do
    resources :comments, only:[:index, :create, :destroy]
    resources :likes, only:[:create, :destroy]
  end

  resources :users, only: [:show, :new, :create, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # UPDATE USER
  get "users/:id/password" => "users#edit_password", as: :user_password
  patch "users/:id/password" => "users#update_password"
  # UPDATE USER PROFILE
  get "users/:id/edit_profile" => "users#edit_profile", as: :user_profile
  patch "users/:id/edit_profile" => "users#update_profile"

  get "users/:id/edit_experience" => "users#edit_experience", as: :user_experience
  patch "users/:id/edit_experience" => "users#update_experience"

  get "users/:id/edit_project" => "users#edit_project", as: :user_project
  patch "users/:id/edit_project" => "users#update_project"

  get "users/:id/edit_opening" => "users#edit_opening", as: :user_opening
  patch "users/:id/edit_opening" => "users#update_opening"

  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment_body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only:[:create, :destroy]
  before_action :authorize!, only:[:edit, :update, :destroy]

  def create
    @comment = Comment.new params.require(:comment).permit(:comment_body)
    @post = Post.find params[:post_id]
    @comment.post = @post
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html {redirect_to posts_path}
        format.js {render :create_success}
      else
        flash[:alert] = "Please fix errors below"
        format.html {render "/posts/index"}
        format.js {render :create_failure}
      end
    end
  end

  # def update
  #   post = Post.find params[:id]
  #   comment = Comment.find params[:id]
  #   byebug
  #   comment.update_attribute(:comment_body, params[:comment][:comment_body])
  # end

  def destroy
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to posts_path, notice: "Comment deleted"}
      format.js {render}
    end
  end

  def authorize!
    @comment = Comment.find params[:id]
    redirect_to root_path, alert: "Access denied" unless can? :manage, @comment
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_create_comm.html.erb
<div id="<%= post.id %>">
	<% if @comment %>
		<div class="create-comm">
			<%= simple_form_for [post, @comment], remote: true do |f| %>
				<div class="row">
					<div class="col-lg-2 col-md-3 col-sm-3 col-xs-3">
						<%= image_tag current_user.profile_picture.url, class: "post-user-pic-comm"%>
					</div>
					<div class="col-lg-10 col-md-9 col-sm-9 col-xs-9">
						<%= f.input :comment_body, label: false %>
					</div>
					<!-- <%= f.submit class: "btn btn-primary"%> -->
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/comments/_show_comm.html.erb
	<div id="<%= dom_id(comment) %>">
		<div class="comm-background">
			<%= image_tag comment.user.profile_picture.url, class: "post-user-pic-comm"%>
			<% if can? :manage, comment %>
				<div class="edit-delete">
					<%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, post_comment_path(post, comment),
																method: :delete,
																remote: true,
																data: {confirm: "Are you sure you want to delete your comment?"}%>
				</div>
			<% end %>
			<%= comment.user.full_name %>:
			<%= comment.comment_body %>
		</div>
	</div>

app/views/comments/create_success.html.erb
$('#comments').append('<%= j(render('/comments/show_comm', {comment: @comment, post: @post})) %>');

app/views/comments/destroy.js.erb
$('#<%= dom_id(@comment)%>').fadeOut(1000, function(){
  $(this).remove();
});