config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "welcome#index"
  get 'auth/linkedin', as: :sign_in_with_linkedin
  get 'auth/linkedin/callback' => 'callbacks#linkedin'

  resources :posts do
    resources :comments, only:[:index, :create, :destroy]
    resources :likes, only:[:create, :destroy]
  end

  resources :users, only: [:show, :new, :create, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # UPDATE USER
  get "users/:id/password" => "users#edit_password", as: :user_password
  patch "users/:id/password" => "users#update_password"
  # UPDATE USER PROFILE
  get "users/:id/edit_profile" => "users#edit_profile", as: :user_profile
  patch "users/:id/edit_profile" => "users#update_profile"

  get "users/:id/edit_experience" => "users#edit_experience", as: :user_experience
  patch "users/:id/edit_experience" => "users#update_experience"

  get "users/:id/edit_project" => "users#edit_project", as: :user_project
  patch "users/:id/edit_project" => "users#update_project"

  get "users/:id/edit_opening" => "users#edit_opening", as: :user_opening
  patch "users/:id/edit_opening" => "users#update_opening"

  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  mount_uploader :post_image, PostImageUploader

  validates :post_body, presence: true, length: {minimum: 1}

  def like_for(user)
    likes.find_by_user_id user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_action :authorize!, only:[:edit, :update, :destroy]

  def create
    @post = Post.new post_params
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html {redirect_to posts_path}
        format.js {render :create_success}
      else
        format.html {redirect_to posts_path}
        format.js {render :create_failure}
      end
    end
  end

  def index
    @post = Post.new
    @comment = Comment.new
  end

  def edit
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attribute(:post_body, params[:post][:post_body])
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    respond_to do |format|
      format.html {redirect_to posts_path}
      format.js {render}
    end
  end

  private
  def authorize!
    @post = Post.find params[:id]
    redirect_to root_path, alert: "Access denied" unless can? :manage, @post
  end

  def post_params
    params.require(:post).permit([:post_body, :post_image])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>">
	<div class="post-background">
		<div class="row">
			<div class="col-lg-1">
				<%= image_tag post.user.profile_picture.url, class: "post-user-pic-thumb"%>
			</div>
			<div class="col-lg-11">
				<% if can? :manage, post %>
					<div class="edit-delete">
						<%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, post_path(post),
																			 method: :delete,
																			 remote: true,
																			 data: {confirm: "Are you sure you want to delete your post?"}
																			 %>
					</div>
				<% end %>
				<%= link_to post.user.full_name, user_path(post.user) %>
				<h6> <%= time_ago_in_words(post.created_at) %> ago</h6>
				<div>
					<h3><%= best_in_place_if current_user == post.user, post, :post_body %></h3>
				</div>
				<!-- <div>
					<%# image_tag(post.post_image.url(:medium)) if post.post_image.url(:medium)%>
				</div> -->
				<div class="btn-group">
					<% if can? :like, post %>
						<% user_like = post.like_for current_user%>
							<% if user_like.present? %>
							<%= link_to "Unlike (#{post.likes.count})", post_like_path(post, user_like),
																		method: :delete,
																		class: 'btn btn-like' %>
							<% else %>
								<%= link_to '<i class="fa fa-thumbs-up" aria-hidden="true"></i>Like'.html_safe,
																		post_likes_path(post),
																		method: :post,
																		class: 'btn btn-like' %>
							<% end %>
					<% else %>
						<div class="btn btn-like">
							<i class="fa fa-thumbs-up" aria-hidden="true"></i> Like
						</div>
					<% end %>
					<!-- create comment -->
					<div class="comm-btn btn btn-like">
						Comment
					</div>
				</div>
					<%= render 'comments/create_comm', post: post %>
				<!-- show comments -->
				<div id="comments">
				<% if @comment %>
					<% post.comments.each do |comm|%>
						<%= render 'comments/show_comm', comment: comm, post: post %>
					<% end %>
				<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/create_success.html.erb
$('#posts').prepend('<%= j(render('/posts/post', {post: @post})) %>');

app/views/posts/destroy.js.erb
$('#<%= dom_id(@post)%>').fadeOut(1000, function(){
  $(this).remove();
});

app/views/posts/index.html.erb
<div class="container post-index-container">
  <div class="row">
    <div class="col-lg-4 col-md-6">
      <div class="image-resize">
        <%= image_tag current_user.profile_picture.url(:version_profile_image), class: "profile-pic"%>
      </div>
      <div class="form-container">
        <h1 class="center">Create New Post</h1>
        <%= simple_form_for @post, remote: true do |f|  %>
        <div>
          <%= f.input :post_image, label: false %>
        </div>
        <div>
          <%= f.input :post_body, label: false%>
        </div>
        <div>
          <%= f.submit class: "btn btn-default hvr-grow btn-center"%>
        </div>
        <% end %>
      </div>
    </div>
<!-- Show posts -->
    <div class="col-lg-8 col-md-6 post-all">
      <h1 id="all-posts-title">All Posts</h1>
      <div id="posts">
        <% current_user.feed.each do |post| %>
          <%= render "posts/post", post: post %>
        <% end %>
      </div>
    </div>
  </div>
</div>