config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "welcome#index"
  get 'auth/linkedin', as: :sign_in_with_linkedin
  get 'auth/linkedin/callback' => 'callbacks#linkedin'

  resources :posts do
    resources :comments, only:[:index, :create, :destroy]
    resources :likes, only:[:create, :destroy]
  end

  resources :users, only: [:show, :new, :create, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # UPDATE USER
  get "users/:id/password" => "users#edit_password", as: :user_password
  patch "users/:id/password" => "users#update_password"
  # UPDATE USER PROFILE
  get "users/:id/edit_profile" => "users#edit_profile", as: :user_profile
  patch "users/:id/edit_profile" => "users#update_profile"

  get "users/:id/edit_experience" => "users#edit_experience", as: :user_experience
  patch "users/:id/edit_experience" => "users#update_experience"

  get "users/:id/edit_project" => "users#edit_project", as: :user_project
  patch "users/:id/edit_project" => "users#update_project"

  get "users/:id/edit_opening" => "users#edit_opening", as: :user_opening
  patch "users/:id/edit_opening" => "users#update_opening"

  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="home-footer footer navbar-bottom">
    <div class="home-footer-left">
      <div><a class="lobster hvr-grow" href="http://localhost:3000/"><span id="six-degrees">6Degrees</span>&nbsp;&nbsp;<span id="for">for</span><span id="web-dev">Web Developers</span></a></div>
      <div><%= link_to "About"%></div>
      <div><%= link_to "Contact"%></div>
    </div>
    <div class="home-footer-right">
      <div class="hvr-grow"><%= image_tag "codecore-logo.png", class: "codecore-logo" %></div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container topnav">
    <div class="nav-bar header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand topnav lobster hvr-grow" href="http://localhost:3000/"><span id="six-degrees">6Degrees</span>&nbsp;&nbsp;<span id="for">for</span><span id="web-dev">Web Developers</span></a>
    <div class="collapse navbar-collapse">
      <ul class= "nav navbar-nav navbar-right" role="tablist">
        <% if user_signed_in? %>
          <li id="welcome-name">Welcome, <%= current_user.first_name %>!</li>
          <li class= "hvr-grow"><%= link_to "Home", posts_path %></li>
          <li class= "hvr-grow"><%= link_to "Profile", user_path(current_user) %></li>
          <li class="dropdown">
            <a class="dropdown-toggle hvr-grow" id="dropdown-toggle" data-toggle="dropdown" href="#">Settings<span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-background">
              <li class="dropdown-hover hvr-grow"><%= link_to "Edit Profile",  user_profile_path(current_user), class: "nav-links"  %></li>
              <li class="dropdown-hover hvr-grow"><%= link_to "Edit Experience",  user_experience_path(current_user), class: "nav-links"  %></li>
              <li class="dropdown-hover hvr-grow"><%= link_to "Edit Projects",  user_project_path(current_user), class: "nav-links"  %></li>
              <li class="dropdown-hover hvr-grow"><%= link_to "Edit Openings",  user_opening_path(current_user), class: "nav-links"  %></li>
              <li role="separator" class="divider"></li>
              <li class="dropdown-hover hvr-grow"><%= link_to "Edit my Account", edit_user_path(current_user), class: "nav-links"  %></li>
            </ul>
          </li>
          <li class= "hvr-grow"><%= link_to fa_icon('sign-out'), sessions_path, method: :delete %></li>
          <li id="google_translate_element"></li>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle hvr-pulse" id="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>
            <span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-background">
              <li class="dropdown-hover"><%= link_to "Register", new_user_path, class: "nav-links"  %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Sign In', '#', id: "sign-in-link", data: { popup_open: "popup-1" }  %></li>
                <%= render 'sessions/sign_in_form' %>
              <li class="dropdown-hover"><%= link_to "Sign In with LinkedIn", sign_in_with_linkedin_path, class: "nav-links"  %></li>
            </ul>
          </li>
          <li id="google_translate_element"></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<script type="text/javascript">
  function googleTranslateElementInit() {
    new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
  }
</script>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>6Degrees</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans|Lalezar|Roboto+Slab" rel="stylesheet">
    <!-- Google maps -->
    <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyCXTGY7tDNxJzJcdctQIUTzCaX9k_gilk4"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <!-- Include Date Range Picker -->
    <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

  </head>

  <body id="app-body">
    <%= render '/layouts/navbar' %>
    <div id="body-yield">
      <% if flash[:notice] -%>
        <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= flash[:notice] %></div>
        </div>
      <% end %>
      <% if flash[:alert] -%>
        <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= flash[:alert] %></div>
        </div>
      <% end %>
    <%= yield %>
    </div>
<!-- footer -->
    <%# render '/layouts/footer' %>
  </body>
</html>